version: '3'

volumes:
    certs: {}
    vhostd: {}
    html: {}

services:
    nginx_proxy:
        image: jwilder/nginx-proxy
        restart: always
        ports:
          - "80:80"
          - "443:443"
        volumes:
          - /var/run/docker.sock:/tmp/docker.sock:ro
          - certs:/etc/nginx/certs:ro
          - vhostd:/etc/nginx/vhost.d
          - html:/usr/share/nginx/html
        labels:
          - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy

    letsencrypt:
        image: jrcs/letsencrypt-nginx-proxy-companion
        restart: always
        environment:
          - NGINX_PROXY_CONTAINER=nginx_proxy
        volumes:
            - certs:/etc/nginx/certs:rw
            - vhostd:/etc/nginx/vhost.d
            - html:/usr/share/nginx/html
            - /var/run/docker.sock:/var/run/docker.sock:ro
        depends_on:
          - nginx_proxy


    react:
        build: .
        image: service_ama_maule
        expose:
            - "80"
        environment:
            - VIRTUAL_HOST=webinarsdk.amamaule.cl, www.webinarsdk.amamaule.cl
            - LETSENCRYPT_HOST=webinarsdk.amamaule.cl, www.webinarsdk.amamaule.cl
            - LETSENCRYPT_EMAIL=webinar@amamaule.cl
        depends_on:
            - nginx_proxy
            - letsencrypt